### ISSUE TITLE
Connect the rest of the per page/tax/post settings

### ISSUE THREAD

**Issue by moonmeister** [moonmeister/wp-graphql-seopress#2]
Plugin isn't yet fetching all the things

https://www.seopress.org/support/guides/list-of-all-post-metas-generated-by-seopress/

**Comment by moonmeister** [comment]
Anyone looking to work on this note that list contains SEOPress Pro Items as well. These can be included, however checks will need to be done to veriffy SEOPress Pro is installed.

**Comment by moonmeister** [comment]
Anyone looking to work on this note that list contains SEOPress Pro Items as well. These can be included, however checks will need to be done to veriffy SEOPress Pro is installed.

**Comment by DeathCamel58** [comment]
Will file PR for this tomorrow if no hiccups occur. I feel like I've necro'd your repository. Thanks for starting this project!

**Comment by moonmeister** [comment]
It needed love. I appreciate it. I added you as a collaborator so you can merge stuff and create releases. I'm here if you have questions or want code reviews.
