### ISSUE TITLE
GRAPHQL SEOPRESS FOR STRUCTURED SCHEMA NOT RIGHT

### ISSUE THREAD

**Issue by wrivkap** [moonmeister/wp-graphql-seopress#35]
BACKEND: HEADLESS WORDPRESS w/ GRAPHQL and SEOPRESS
FRONTEND: NEXTJS

USING SEOPRESS WITH GRAPHQL to get the structured schema but instead of getting a readable FAQ LD+Json with ("@context": "https://schema.org", "@type": "FAQPage",)  Im getting the results below: 

GRAPHQL RESULTS:  
        "node": {
            "seo": {
              "canonicalUrl": "",
              "proSchemas": "\"\"",
              "proSchemasManual": "[{\"_seopress_pro_rich_snippets_type\":\"faq\",\"_seopress_pro_rich_snippets_faq\":{\"0\":{\"question\":\"what?\",\"answer\":\"YEs\"},\"2\":{\"question\":\"Who?\",\"answer\":\"Him\"},\"3\":{\"question\":\"When?\",\"answer\":\"!0am\"}}}]",
              "opengraphImage": null,
              "hasProLicense": true

**Expecting something like this:** 
<script type="application/ld+json">
{
	"@context": "https://schema.org",
	"@type": "FAQPage",
	"mainEntity": [
		{
			"@type": "Question",
			"name": "➕ How do I add a question?",
			"acceptedAnswer": {
				"@type": "Answer",
				"text": "Just click on the \"Add a Question\" button at the end of the current questions."
			}
		},
            }

**Comment by DeathCamel58** [comment]
The structured data _is not_ intended to be valid JSON LD. You'll need to parse it out.

On the site I use this for, you can see how I parse this out at the two following links.
https://github.com/DeathCamel58/plumb-all-gatsby/blob/c6171aa7d91480dfe172a79dce7fb06c4bd45110/src/components/seo/SEOPress.js#L135
https://github.com/DeathCamel58/plumb-all-gatsby/blob/master/src/components/seo/ProSchemasManual.js

Hope this helps!
