### ISSUE TITLE
Create JSON LD using graphql

### ISSUE THREAD

**Issue by vkalyaanasundaram** [moonmeister/wp-graphql-seopress#36]
I have GraphQL query response as 

"proSchemasManual": "
[{\"_seopress_pro_rich_snippets_type\":\"faq\",\"_seopress_pro_rich_snippets_faq\":
       {\"0\":{\"question\":\"what?\",\"answer\":\"YEs\"},
       \"2\":{\"question\":\"Who?\",\"answer\":\"Him\"},
      \"3\":{\"question\":\"When?\",\"answer\":\"!0am\"}}
}]",

 I want to generate JSON LD in front end Next.js with 

@context,
@type,
 address and etc.
![proSchema](https://user-images.githubusercontent.com/82804146/165783043-cc895651-8914-41ed-a660-cd057026d037.JPG)

**Comment by moonmeister** [comment]
You'll need to take this structured data and create the JSON LD data. There's a react component I've used for this before but don't recall the name.

Apr 28, 2022 9:02:45 AM vkalyaanasundaram ***@***.***>:

**Comment by DeathCamel58** [comment]
@moonmeister Is right about this.
The structured data _is not_ intended to be valid JSON LD.

On the site I use this for, you can see how I parse this out: https://github.com/DeathCamel58/plumb-all-gatsby/blob/c6171aa7d91480dfe172a79dce7fb06c4bd45110/src/components/seo/SEOPress.js#L135

Hope this helps!
