### ISSUE TITLE
504 GATEWAY_TIMEOUT ERROR

### ISSUE THREAD

**Issue by vkalyaanasundaram** [moonmeister/wp-graphql-seopress#40]
Next.js application, we have created all pages as a static generation. Whenever I am navigating to the page (Ex: Blogs) I am able to see the content without any problems. But when I checked my browser console I was able to see  "504 GATEWAY_TIMEOUT ERROR". Jason. Kindly help us to fix console error.

<img width="691" alt="console-error" src="https://user-images.githubusercontent.com/82804146/181584064-7deda123-efbf-4d2a-a2e6-7bb4b3fb7f34.PNG">

**Comment by moonmeister** [comment]
unrelated to this plugin. please find another support channel.
