### ISSUE TITLE
openGraphImage and twitterImage return null (altText, sourceUrl, srcSet)

### ISSUE THREAD

**Issue by MaSchVam** [moonmeister/wp-graphql-seopress#8]
No matter what I try, all the data related to the social images seem to be missing when I construct my query in GraphiQL?

I can `gatsby develop` successfully, however I am seeing a `warn gatsby-source-wordpress Couldn't find source url for media item #5 ` in the console!

Tested on various posts, all other GraphQL data (including ACF fields) return fine. 

@moonmeister can you confirm?

`Gatsby version  2.24.55`

Gatsby Plugins:
`gatsby-plugin-react-helmet`
`gatsby-plugin-sass`
`gatsby-plugin-offline`
`gatsby-awesome-pagination`
`gatsby-source-filesystem`
`gatsby-plugin-netlify-cache`
`gatsby-transformer-sharp`
`gatsby-plugin-sharp`

And lastly, what I am thinking could be the culprit here, possibly?
`gatsby-source-wordpress-experimental`

I am using `SEOPress 3.9.2` in my installation

Other WP Plugins:
`Advanced Custom Fields PRO`
`Really Simple SSL`
`WP Gatsby`
`WP GraphQL`
`WPGraphQL for Advanced Custom Fields`
`Yoast Duplicate Post`

**Comment by moonmeister** [comment]
Can you share the code that is failing?

**Comment by MaSchVam** [comment]
Nothing really fails, the GraphQL query just returns null for all the image data (altText, sourceUrl, srcSet), even though I definitely have images (with alt texts) saved in my posts. It is also worth noting, that all the other data returns just fine - so I am getting the meta title and excerpts and OG titles.

I've been toying around with it for a little bit. It's really weird.. Especially, since I can successfully query for the URLs on my WordPress install by echo'ing out `get_post_meta( $post->ID, '_seopress_social_fb_img', true );` on the individual posts for example.

However, using this example GraphQL query:

```
{
  wpPost(slug: {eq: "insert-post-slug"}) {
    title
    content
    slug
    id
    seo {
      metaTitle
      metaDesc
      opengraphTitle
      opengraphDescription
      opengraphImage {
        altText
        sourceUrl
        srcSet
      }
      twitterTitle
      twitterDescription
      twitterImage {
        altText
        sourceUrl
        srcSet
      }
    }
  }
}
```
The data is just not there 🤔

**Comment by moonmeister** [comment]
I'd start by trying to fetch this data in GraphiQL on the WP side, then in the Gatsby side. That'll tell us what's happening. There have also been some big schmea changes in WPGraphQL since I made this plugin so it might be broken with new versions or require schema mods such as 

```graphql
twitterImage {
  node {
     altText
     sourceUrl
     srcSet
  }
}
```

**Comment by moonmeister** [comment]
If you don't mind using Yoast the WPGraphQL integration for it is much better FYI.

**Comment by MaSchVam** [comment]
> I'd start by trying to fetch this data in GraphiQL on the WP side, then in the Gatsby side. That'll tell us what's happening. 
> 
> ```graphql
> twitterImage {
>   node {
>      altText
>      sourceUrl
>      srcSet
>   }
> }
> ```

Sure - believe it or not, I actually tried this already, which results in a `Cannot query field \"node\" on type \"WpMediaItem\"` error 😃

>There have also been some big schmea changes in WPGraphQL

I had a look at the plugin, and then the WPGraphQL documentation - and I think this is probably the issue. Looks like a lot has changed in the since then. I'll have a look at the Yoast option instead 👍
